stages:
  - build
  - deploy

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

build_vue:
  stage: build
  image: node:20.19.0
  variables:
    NODE_OPTIONS: "--max-old-space-size=4096"
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  only:
    - main


# ====== DEPLOY TO DEPLOY BRANCH ======
deploy_to_branch:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git
    - git config --global user.email "gitlab-ci@local"
    - git config --global user.name "GitLab CI"
  script:
    - git clone --branch production $CI_REPOSITORY_URL production-branch
    - rsync -av --delete dist/ production-branch/
    - cd production-branch
    - git add .
    - git commit -m "production from pipeline $CI_PIPELINE_ID" || echo "No changes to commit"
    - git push origin production
  only:
    - main