version: '3.8'

services:
  sewing-dev:
    build: .
    container_name: sewing-dev  # Explicit name lebih baik
    # command: npm run dev -- --host
    volumes:
      - .:/app              # Mount seluruh folder
      - /app/node_modules # Untuk menghindari masalah dengan node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sewing-dev.rule=Host(`vue.sewing.localhost`)"
      - "traefik.http.routers.sewing-dev.entrypoints=web"
      - "traefik.http.routers.sewing-dev.service=sewing-dev"
      - "traefik.http.routers.sewing-dev.middlewares=websocket-headers@file"
      - "traefik.http.services.sewing-dev.loadbalancer.server.port=5173"  
    networks:
      - shared
    ports:
      - "5173:5173"  # Untuk development access langsung

networks:
  shared:
    external: true